# Generated by Django 5.1.2 on 2024-10-30 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nusp', models.PositiveBigIntegerField(unique=True)),
                ('rg', models.PositiveIntegerField()),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno'), ('coordenador', 'Coordenador'), ('orientador', 'Orientador')], max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
