# Generated by Django 5.1.2 on 2024-10-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nusp',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rg',
            field=models.CharField(max_length=11),
        ),
    ]
