# Generated by Django 5.1.2 on 2024-11-17 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failed_courses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='passed_courses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('creditos', models.CharField(max_length=10)),
                ('carga_horaria_semanal', models.CharField(max_length=50)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.profile')),
            ],
        ),
    ]
