# Generated by Django 5.1.2 on 2024-11-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_relatorio_nusp'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='segunda_avaliacao',
            field=models.BooleanField(default=False),
        ),
    ]
