# Generated by Django 5.1.2 on 2024-12-08 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_relatorio_segunda_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='conceito_coordenador',
            field=models.CharField(blank=True, choices=[('adequado', 'Adequado'), ('adequado_com_ressalvas', 'Adequado com Ressalvas'), ('insatisfatorio', 'Insatisfatório')], max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='conceito_orientador',
            field=models.CharField(blank=True, choices=[('adequado', 'Adequado'), ('adequado_com_ressalvas', 'Adequado com Ressalvas'), ('insatisfatorio', 'Insatisfatório')], max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_orientador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('avaliado_orientador', 'Avaliado pelo Orientador'), ('avaliado_coordenador', 'Avaliado pelo Coordenador')], default='pendente', max_length=20),
        ),
    ]
